### PR TITLE
Issue #444: Search Bar Language Code Typeahead drop down thingy

### PR DESCRIPTION
**Pull request by phillip-hopper**
Try it at http://test-door43.org.s3-website-us-west-2.amazonaws.com/en/.

Implements #444.

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
@phillip-hopper - not seeing the link to the original issue.

**Comment by PhotoNomad0** [comment]
@phillip-hopper went to the website listed and seems to be problem.  If I type 'e', I don't see anything.  Then add an 'n', still don't see anything, then if I add a 'g' I will see some matches on 'eng'.  If I hit backspace, I will see matches on 'en'.  If I type 'hi' I will see matches.  Then if I quickly backspace and type 'en' I will see matches.  Seems like a timing issue.

**Comment by phillip-hopper** [comment]
@PhotoNomad0 I will not search on just one character. We tried that and it is too slow because it returns thousands of results which must then be sorted. It searches once you type the second character, and there is a small delay built in so it won't query the server until there is a short pause, for the same reason, the response time to retrieve and sort the list is too long. So if you type `en` and pause, you should see the list with English at the top.

**Comment by PhotoNomad0** [comment]
@phillip-hopper - did you try to reproduce my steps?  I am still often not seeing any matches if I type 'e', wait and then type 'n'.

**Comment by PhotoNomad0** [comment]
@phillip-hopper - seeing the problem with both chrome and safari.  But it is not consistent.  Sometimes I will see a match for en, but if do two backspaces and type in en again quickly I will often 
get no matches.

**Comment by phillip-hopper** [comment]
@PhotoNomad0 It is currently set to not repeat a search twice in a row, so it doesn't search for `en` after it already displayed those results. This is the same as it has worked on dw.door43.org for several years. And it will never search for a single character even after a pause, it must have at least 2.

**Pull request merged**
